// Fallback data when Supabase is not configured
export const fallbackProducts = [
  {
    id: "1",
    name: "Royal Street Hoodie",
    category: "Unisex Fashion",
    price: "₦45,000",
    image: "/IMG-20250618-WA0001.jpg",
    cloudinary_public_id: null,
    description: "Premium streetwear meets luxury comfort",
    badge: "Trending",
    is_active: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Gold Chain Luxury Set",
    category: "Jewelry",
    price: "₦120,000",
    image: "/placeholder.svg?height=400&width=300",
    cloudinary_public_id: null,
    description: "18k gold-plated statement piece",
    badge: "Limited",
    is_active: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "MINIS Signature Snapback",
    category: "Accessories",
    price: "₦25,000",
    image: "/placeholder.svg?height=400&width=300",
    cloudinary_public_id: null,
    description: "Custom embroidered premium cap",
    badge: "New Drop",
    is_active: true,
    sort_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Luxury Tracksuit Set",
    category: "Unisex Fashion",
    price: "₦85,000",
    image: "/placeholder.svg?height=400&width=300",
    cloudinary_public_id: null,
    description: "Italian fabric, Nigerian craftsmanship",
    badge: "Best Seller",
    is_active: true,
    sort_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Diamond Stud Earrings",
    category: "Jewelry",
    price: "₦75,000",
    image: "/placeholder.svg?height=400&width=300",
    cloudinary_public_id: null,
    description: "Cubic zirconia premium finish",
    badge: "Exclusive",
    is_active: true,
    sort_order: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Designer Cargo Pants",
    category: "Fashion",
    price: "₦55,000",
    image: "/placeholder.svg?height=400&width=300",
    cloudinary_public_id: null,
    description: "Military-inspired luxury streetwear",
    badge: "Hot",
    is_active: true,
    sort_order: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const fallbackTestimonials = [
  {
    id: "1",
    name: "Adunni Ade",
    role: "Nollywood Actress",
    content: "Minis Umar transformed my entire wardrobe. The attention to detail and luxury pieces are unmatched!",
    rating: 5,
    is_active: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "David Adeleke",
    role: "Music Executive",
    content: "From red carpet events to casual street looks, MINIS LUXURY delivers excellence every time.",
    rating: 5,
    is_active: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Temi Otedola",
    role: "Fashion Influencer",
    content: "The personal shopping experience is world-class. Umar has an eye for luxury that's truly exceptional.",
    rating: 5,
    is_active: true,
    sort_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Burna Boy",
    role: "Grammy Winner",
    content: "MINIS LUXURY understands my style perfectly. Every piece tells a story and makes a statement.",
    rating: 5,
    is_active: true,
    sort_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Tiwa Savage",
    role: "Afrobeats Queen",
    content: "The quality and craftsmanship are exceptional. Umar has an incredible eye for luxury fashion.",
    rating: 5,
    is_active: true,
    sort_order: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const fallbackSettings = {
  brand_name: "MINIS LUXURY",
  tagline: "Where Nigerian Street Fashion Meets Global Luxury",
  hero_title: "MINIS LUXURY",
  hero_subtitle: "Where Nigerian Street Fashion Meets Global Luxury",
  founder_name: "Muhammed Umar Faruq",
  founder_title: "Founder & Creative Director",
  about_text:
    "From the vibrant streets of Nigeria to the global luxury fashion scene, Muhammed Umar Faruq has built MINIS LUXURY into the premier destination for discerning fashion enthusiasts.",
  instagram_handle: "@Minis_Luxury",
  whatsapp_number: "2349057244762",
  business_email: "hello@minisluxury.com",
  business_address: "Victoria Island, Lagos, Nigeria",
  business_hours: "Mon-Sat: 10AM-8PM",
  delivery_info: "Free delivery within Lagos. Nationwide shipping available.",
  return_policy: "30-day return policy on all items.",
}
